language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
    - dist
jobs:
  include:
    - stage: build
      install: yarn
      script:
        - rm -rf dist
        - yarn build
        - yarn build --base-href /userStudy/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: SHA256:KWtU+fkuf5U4Io/YgVZQy2dkcIqjuwtqF4KfKflrH+k
  keep_history: true
  on:
    branch: master

