version: '3'

services:
  frontend:
    build: frontend
    networks:
      - main

  mongo:
    hostname: mongo
    image: mongo:4.2
    networks:
      - main
    expose:
      - 27017
    volumes:
      - ./data:/data/db

  backend:
    build: backend
    networks:
      - main
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo/try
    depends_on:
      - mongo

networks:
  main:

